name: Build ARMv6

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: arm-unknown-linux-musleabihf
      artifact: sshx-linux-armv6