name: Build AMD64

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: x86_64-unknown-linux-musl
      artifact: sshx-linux-amd64