name: Build All Platforms

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  #
  # 读取 Cargo.toml 版本号
  #
  version:
    name: Read Version
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Read Version
        id: version
        shell: bash
        run: |
          VERSION=$(grep '^version' Cargo.toml | head -1 | cut -d'"' -f2)

          echo "Detected version: $VERSION"

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  #
  # AMD64
  #
  amd64:
    needs: version
    uses: ./.github/workflows/reusable-build.yml

    with:
      target: x86_64-unknown-linux-musl
      artifact: sshx-linux-amd64

    secrets:
      SSHX_DEFAULT_SERVER: ${{ secrets.SSHX_DEFAULT_SERVER }}

  #
  # ARM64
  #
  arm64:
    needs: version
    uses: ./.github/workflows/reusable-build.yml

    with:
      target: aarch64-unknown-linux-musl
      artifact: sshx-linux-arm64

    secrets:
      SSHX_DEFAULT_SERVER: ${{ secrets.SSHX_DEFAULT_SERVER }}

  #
  # ARMv7
  #
  armv7:
    needs: version
    uses: ./.github/workflows/reusable-build.yml

    with:
      target: armv7-unknown-linux-musleabihf
      artifact: sshx-linux-armv7

    secrets:
      SSHX_DEFAULT_SERVER: ${{ secrets.SSHX_DEFAULT_SERVER }}

  #
  # ARMv6
  #
  armv6:
    needs: version
    uses: ./.github/workflows/reusable-build.yml

    with:
      target: arm-unknown-linux-musleabihf
      artifact: sshx-linux-armv6
      rustflags: "-C target-feature=+crt-static -C target-cpu=arm1176jzf-s"

    secrets:
      SSHX_DEFAULT_SERVER: ${{ secrets.SSHX_DEFAULT_SERVER }}

  #
  # 汇总
  #
  package:
    name: Package All
    runs-on: ubuntu-latest

    needs:
      - version
      - amd64
      - arm64
      - armv7
      - armv6

    steps:
      - name: Download AMD64
        uses: actions/download-artifact@v4
        with:
          name: sshx-linux-amd64-v${{ needs.version.outputs.version }}
          path: release/amd64

      - name: Download ARM64
        uses: actions/download-artifact@v4
        with:
          name: sshx-linux-arm64-v${{ needs.version.outputs.version }}
          path: release/arm64

      - name: Download ARMv7
        uses: actions/download-artifact@v4
        with:
          name: sshx-linux-armv7-v${{ needs.version.outputs.version }}
          path: release/armv7

      - name: Download ARMv6
        uses: actions/download-artifact@v4
        with:
          name: sshx-linux-armv6-v${{ needs.version.outputs.version }}
          path: release/armv6

      - name: Show Files
        shell: bash
        run: |
          echo "======================"
          find release -type f
          echo "======================"

      - name: Create ZIP
        shell: bash
        run: |
          cd release
          zip -r ../sshx-all-platforms-v${{ needs.version.outputs.version }}.zip .

      - name: Upload Combined Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sshx-all-platforms-v${{ needs.version.outputs.version }}
          path: sshx-all-platforms-v${{ needs.version.outputs.version }}.zip