name: Reusable Build

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

      artifact:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install protoc
        uses: arduino/setup-protoc@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ inputs.target }}

      - name: Install musl
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build sshx
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: |
          cargo build \
            --release \
            --target ${{ inputs.target }} \
            -p sshx

      - name: Strip binary
        run: |
          strip target/${{ inputs.target }}/release/sshx || true

      - name: Verify
        run: |
          file target/${{ inputs.target }}/release/sshx
          ldd target/${{ inputs.target }}/release/sshx || true

      - name: Package
        run: |
          mkdir -p dist

          cp \
            target/${{ inputs.target }}/release/sshx \
            dist/sshx

          tar -C dist -czf \
            ${{ inputs.artifact }}.tar.gz \
            sshx

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.artifact }}.tar.gz